seisflows/preprocess/base.py, seisflows/seistools/readers.py, seisflows/seistools/writers.py
Future Obspy releases will remove obspy.segy.core. Dropped '/', duplicated in reader/writer routines.
=> updated deprecated obspy read/write calls

seisflows/system/pbs_torque_sm.py, seisflows/system/wrappers/export_paths.sh
Adds a pbs_torque_sm class. Shell script acts as a wrapper to export required environment variables to pbsdsh spawns. Note mpiargs is provided and is intended to be invoked by the solver.base.mpirun routine. Calls MPI code as an MPI singleton due to pbsdsh limitations.
=> PBS torque class added

seisflows/seistools/readers.py, seisflows/system/mpi.py, seisflows/system/wrappers/run_mpi, seisflows/system/wrappers/run_mpi_head
Adds an MPI system class for task parallelism using mpi4py. Designed to be used with serial/non-mpi solvers and can be readily transported between regular machines and cluster environments. Submit function could be adjusted to resemble cluster qsub/sbatch commands if necessary. Has shown to be more stable than pbsdsh thus far. 
Open-MPI warns about calling calling fork(), system(), or popen() in MPI processes but assuming the workflow is designed correctly (i.e. function calls are to independent events/cause no conflicts, this should be safe.
=> Added MPI system class

seisflows/seisflows.py, seisflows/system/frontera.py, seisflows/system/slurm.py, seisflows/workflow/test_flow.py
This PR gets SeisFlows working on Frontera, and includes a few bug fixes of the SeisFlows command line tool. 
Frontera, a Texas Advanced Computing Center (TACC) supercomputer, is a SLURM based system, and therefore builds off the SLURM system module that was already written into SeisFlows. Needed to work out some key differences between Frontera and the standard SLURM implementation to get things working:
1) Frontera (and TACC supercomputers in general) does __not__ allow submitting SBATCH jobs from compute nodes, which is how SeisFlows operates (i.e., a master job on a compute node submits simulation jobs). To side step this the system.run() function SSH's from the compute node into the login node before submitting new SBATCH jobs (thanks to Ian Wang for the suggestion). During the run() …
=> Feature frontera support

seisflows/examples/ex2_specfem2d_workstation_inversion_w_pyatoa.py, seisflows/examples/sfexample2d.py, seisflows/seisflows.py
Updating 2D examples so that the 'specfem2d' directory can be input from the command line rather than via an input() statement. This is necessary as running SeisFlows through 'docker run' will break when encountering an input statement so we need to feed in this information from the command line. This new call looks like:
seisflows examples run 1 --specfem2d_repo path/to/specfem2d  # or -r
Example problems now also look in '${pwd}/specfem2d' if no '-r' option given, and if it cant find a matching directory, it will fall back to downloading the latest SPECFEM2D devel version, configuring and compiling.
=> update 2D examples

seisflows/tools/graphics.py, seisflows/tools/specfem.py
Hi Bryant,
This patch adds `plot_2d_image` function and uses it in `seisflows.tools.specfem.Model` 
It adds NaN values to the top edge of the model before interpolation to the regular grid. In order to fix the representation issue with complex topographies. I have also tested with flat topography, it didn't cause problems.
I couldn't it make it work tricontourf. Feel free to explore similar fix for it. `plot_2d_image` might be slower than `plot_2d_contour` since it uses imshow which requires a interpolated regular grid.
Comparison image for the `simple_topography_and_also_a_simple_fluid_layer` specfem2D model.
```python
from seisflows.tools.specfem import Model
m = Model("DATA")
m.plot2d(parameter="vs")
```
=> Plot 2D improvement for models with complex topographies

seisflows/optimize/gradient.py, seisflows/preprocess/default.py, seisflows/preprocess/pyaflowa.py, seisflows/workflow/forward.py, seisflows/workflow/inversion.py
Hi @bch0w,
I detected and fixed 4 problems that occurred during the line search:
1. **Residuals were incorrectly written sometimes.** The residuals from all events were written to the same file, i.e., `residuals.txt`. This means that different MPI processes wrote to `residuals.txt` at the same time. On some occasions this resulted in the following:
residual1
residual2
residual3residual4
which caused `np.loadtxt('residuals.txt')` to fail on reading the file. I modified SeisFlows so residuals are written to one file per event, that is, `residuals_event_iteration_stepcount.txt`. This modification fixes the problem. Also, it helps to know how many measurements are taken per event during each iteration. It may be a good idea to also write the observation name for tracking purposes.
2. …
=> Fixed problems during line search plus other minor changes

pyproject.toml, seisflows/optimize/gradient.py, seisflows/plugins/line_search/bracket.py, seisflows/preprocess/pyaflowa.py, seisflows/system/workstation.py, seisflows/workflow/forward.py, seisflows/workflow/inversion.py, seisflows/workflow/migration.py, seisflows/workflow/noise_inversion.py
- Added Preprocess.Pyaflowa parameter `revalidate` which will revalidate misfit windows when parameter `fix_windows` is 'ITER' or True. Windows which do not fall into the acceptable criteria (time shift, dlna) will be removed. Previously all windows which had been previously gathered were re-used, which led to issues of cycle skipping or very large time shifts that would stall an inversion
- Fixed up Pyaflowa processing log messaging to match the remainder of the SeisFlows logs and to be more apparent when a processing step has failed
- Bump Pyatoa dependency to 0.4.0 to access latest Pyatoa release features
- Pyaflowa preprocessing now allows for specific components to be selected during window retrieval which reduces chance of error due to mismatching components
- Added a print function …
=> Improving Pyaflowa preprocessing and additional bugfixes

environment.yml, pyproject.toml, seisflows/tools/specfem.py
Hi!
I am trying to install Seisflows, but I needed to modify the version of pyatoa to be installed with conda, because of the error below. Do you think this workaround would work? Thank you!
```
The conflict is caused by:
The user requested pyatoa>=0.3.0
seisflows 3.0.0 depends on pyatoa>=0.4.0
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```
=> pyatoa 0.4.0 cannot be specified.

seisflows/examples/ex3_fwd_solver.py, seisflows/examples/sfexample2d.py, seisflows/optimize/gradient.py, seisflows/plugins/preprocess/misfit.py, seisflows/preprocess/default.py, seisflows/preprocess/pyaflowa.py, seisflows/seisflows.py, seisflows/solver/specfem.py, seisflows/tools/graphics.py, seisflows/tools/msg.py, seisflows/tools/specfem.py, seisflows/workflow/forward.py, seisflows/workflow/inversion.py
This PR fixes examples in the `devel` branch after some API changes had broken them, which includes updates and bugfixes to the Solver and Preprocessing modules. Currently all 3 examples are now working and generally matching previous results. Most importantly, fixes some critical bugs that were introduced to the Default preprocessing module in #181 
- Updates parameter names to match updates that originally broke examples in #181 
- Adds developer 'serial' mode for Default preprocessing for better debugging
- Critical: Default `trim` function was swapping obs and syn waveforms leading to incorrect misfit and adjoint sources
- Critical: Removes previous update to traveltime misfit function which did not allow negative misfit, causing incorrect adjoint sources, while retaining requirement …
=> Fixes examples and bugfixes solver  and default preprocessing module

CHANGELOG.md, docs/conf.py, pyproject.toml, seisflows/seisflows.py, seisflows/tools/specfem.py
An update to the SPECFEM2D parameter file (dev branch) broke the function that gets and sets velocity model parameters in the Par_file. Previously this function relied on looking for parameters above and below the model (since the model did not follow the standard key=val structure), however the parameter below the model changed so the function no longer worked. Anyways this was pretty hardcoded so was in need of an update.
Function has been updated to now look for file lines matching the structure of the SPECFEM2D velocity model. An internal function `_getidx_vel_model` was written to be used by both getter and setter. The SeisFlows command line tool as updated accordingly and this was tested on both master and devel branches of SPECFEM2D and retains the same behavior as before. This …
=> Hotfix: Fixing incompatibility with updated SPECFEM2D parameter file

CHANGELOG.md, pyproject.toml, seisflows/solver/specfem.py, seisflows/workflow/forward.py
Small PR for some inconsistencies causing the examples to not work. 
- Missing solver parameter `prune_scratch` causing SPECFEM2D to fail
- Incorrect boolean check causing forward workflow to fail
- Bump Devel version number 3.1.0 -> 3.1.1
=> Bugfix examples not working

environment.yml, pyproject.toml, seisflows/examples/sfexample2d.py, seisflows/optimize/LBFGS.py, seisflows/optimize/gradient.py, seisflows/plugins/line_search/bracket.py, seisflows/preprocess/default.py, seisflows/preprocess/pyaflowa.py, seisflows/seisflows.py, seisflows/solver/specfem.py, seisflows/system/cluster.py, seisflows/system/workstation.py, seisflows/tests/test_solver.py, seisflows/workflow/inversion.py, seisflows/workflow/noise_inversion.py
Previously `Thrifty` mode (where line search results from iteration I are used to replace the forward simulations of iteration I + 1) was not properly implemented into the NoiseInversion workflow. This PR improves that functionality and also adds some QoL features and fixes:
- **New parameter**: `optimize.step_len_min` allows the User to set a minimum step length (alpha) as a percentage of the model values. This prevents line searches from trying to minimize misfit with very small model changes, which is a waste of computational resources. 
- **Changed Behavior**: Saved Forward arrays are now overwritten by new forward simulations, for the case when Thrifty line searches need access to forward arrays in subsequent adjoint simulations
- **QoL Improvement**: Initial and True model file …
=> Implement Thrifty Inversion for NoiseInversion

CHANGELOG.md, pyproject.toml, seisflows/preprocess/pyaflowa.py, seisflows/system/fujitsu.py, seisflows/workflow/migration.py
Small update to fix a bug in Wisteria system module that accumulated a ',' in the environment variables so that the second time `system.run` was called it would lead to an error. Some small additional riders are included.
- Bugfix Fujitsu/Wisteria environ variable was being updated internally, causing an accumulating error
- Bugfix: Removed Pyaflowa preprocess normalization step as this was hardcoded for some personal research tasks, not meant to be in code
- Added a tasktime multiplier to Inversion kernel postprocessing tasks, eventually this should be accessible via the State system or parameter file but for now making it part of the source code
- Removes main install instruction pointing to Pyatoa GitHub, points to PyPi now by default
- Updates [dev] install instructions to point …
=> Bugfix System Fujitsu/Wisteria environs

CHANGELOG.md, pyproject.toml, seisflows/solver/specfem.py, seisflows/system/cluster.py, seisflows/system/runscripts/submit_workflow.py, seisflows/workflow/forward.py, seisflows/workflow/noise_inversion.py
Only relevant for 'noise_inversion' workflows. The `generate_data` option which runs forward simulations through the target model ('path_model_true') was not implemented for the 'noise_inversion' workflow. This PR implements that functionality and allows generation of ZZ, RR and TT synthetic greens functions that can be used as 'observed' data for a synthetic inversion. Simply setting the parameter `generate_data`==True in the parameter file will implement this option. Some additional aesthetic riders.
- Fixes synthetic inversion data generation for noise inversion workflow
- Fixes some flag misnaming in Forward workflow synthetic inversion data generation
- Adjusts main log message aesthetics to provide a visual marker for new job submissions
=> Fixes 'generate_data' option for noise inversion

CHANGELOG.md, pyproject.toml, seisflows/preprocess/pyaflowa.py, seisflows/workflow/migration.py
Small update that bug fixes finalization for Pyaflowa preprocessing module.
@aakash10gupta pointed out that figures/logs were being deleted during the finalization task when using the Pyaflowa preprocessing module. This was due to a change that tried to accommodate additional tags on the figures and log files necessary for the noise inversion workflows, which ended up breaking for normal inversion workflows.
- Fixes logs and figures getting deleted but not saved during Pyaflowa finalization
- Changes finalization behavior to not delete logs/figures from scratch directory, if User requests no export
- Removes hardcoded tasktime increase for postprocessing tasks which was accidentally left in from development
=> Bugfix Pyaflowa finalization tasks

CHANGELOG.md, pyproject.toml, seisflows/preprocess/pyaflowa.py
Adds better traceback information when preprocessing fails with Pyaflowa preprocess module, before it was too generic and had no traceback information so it was impossible to determine where errors were occurring.
=> Improve Pyaflowa error logging

CHANGELOG.md, pyproject.toml, seisflows/preprocess/default.py, seisflows/preprocess/pyaflowa.py, seisflows/seisflows.py, seisflows/solver/specfem.py, seisflows/system/fujitsu.py, seisflows/system/runscripts/custom_run-wisteria, seisflows/system/wisteria.py, seisflows/workflow/forward.py, seisflows/workflow/test_flow.py
General improvements to the U. Tokyo Fujitsu cluster Wisteria and multi-GPU workflows.
- Overhauled `Fujitsu` System class to now allow parameter `ntask_max`. This is not an inherent option in Fujitsu-brand clusters so I needed to code it up directly in SeisFlows. General architecture is that SeisFlows submits `ntask_max` jobs to the System and monitors them, whenever a job completes, a new job is submitted to take its place, until `ntask` jobs have completed.
- Replace some default module loading in Wisteria custom run scripts to not use CUDA-aware MPI as this is not used in SPECFEM3D_Cartesian
- Shifted `residuals` directory creation into the responsibility of Workflow module, rather than preprocessing module, to keep dir. creation high-level
- Bugfix: Default preprocessing was not …
=> Improves System sub-class Wisteria

CHANGELOG.md, environment.yml, pyproject.toml, seisflows/optimize/gradient.py, seisflows/plugins/line_search/backtrack.py, seisflows/plugins/line_search/bracket.py, seisflows/solver/specfem.py, seisflows/solver/specfem2d.py, seisflows/solver/specfem3d.py, seisflows/solver/specfem3d_globe.py, seisflows/tools/config.py, seisflows/tools/model.py, seisflows/workflow/inversion.py
See Issue #229 for description of the issue, relating to slow I/O for dictionaries of arrays being saved with NumPy savez. This PR replaces all that functionality with direct read/write ability in the native SPECFEM format (currently only GLL Fortran binary is supported, but kept general for future use with ADIOS format). Removes all references to .npz files used previously for model and gradient storage.
- Replaces Optimize.gradient `save_vector` and `load_vector` functions internal I/O for Model class with read/write in native SPECFEM format, rather than in the middle-man .npz format which was taking excessive time
- Models in the Optimization module are now saved in directories rather than as single files
- Replaces all occurrences of .npz with references to the Model paths
- Cleans up …
=> Improve Model I/O speeds + QoL upgrades

CHANGELOG.md, pyproject.toml, seisflows/system/cluster.py, seisflows/system/fujitsu.py, seisflows/system/slurm.py
The `Fujitsu` and child `Wisteria` classes did not have access to custom tasktimes like Slurm-derived system classes so we were unable to increase tasktimes for long tasks like smoothing. This PR implements that and adds a few bugfixes.
- Implements custom tasktimes in Fujitsu system
- Modifies Fujitsu run_call structure to be more like Slurm system
- Bugfix Fujitsu tasktime and walltime were not able to exceed 1 day
- Bugfix: Slurm system class was using an undefined parameter
=> Fujitsu feature custom tasktime

seisflows/preprocess/pyaflowa.py
Adds toggles in the parameter file to turn off certain preprocessing steps when using the Pyaflowa preprocessing module. Toggles include `standardize`, `preprocess` and `window`. Each one turns off one of the Pyatoa Manager functions (of the same name). By default they are all on to match original behavior.
=> Feature: Pyaflowa preprocessing toggles

pyproject.toml, seisflows/seisflows.py, seisflows/tools/graphics.py, seisflows/tools/model.py
Improves the SeisFlows command line tool `seisflows plot2d` which is used for quickly plotting models/gradients/kernels from 2D problems, mostly used for visualizing results during SeisFlows examples problems.
New options include:
- cmap: choose Matplotlib colormap
- levels: discretization level of the colormap
- center_cmap: force colormap to center around zero. This is done by default for kernels but might be useful for other plotting
- vmin: choose lower bound of the colorbar
- vmax: choose upper bound of the colorbar
- noshow: do not show the GUI figure, useful if scripting this function
Bugfix includes being able to change colormap, before the function was failing with custom colormap inputs
Example below
```bash
seisflows plot2d GRADIENT_01 vs_kernel --cmap jet --levels 31 …
```
=> Improve plot2d example graphics
